; Globals
(global short ui_location -1)
(global real mainmenu_offset 0)
(global long wait_ticks 0)
(global short ui_location_clock_start -1)

; Externs

; Scripts
(script static void (sleep_ui (long timer_ticks))
	(print "sleep ui script")
	(set ui_location_clock_start ui_location)
	(set wait_ticks 0)
	(sleep_until (begin
		(set wait_ticks (+ wait_ticks 1))
		(if (!= ui_location ui_location_clock_start)
			(set wait_ticks timer_ticks)
		)
		(>= wait_ticks timer_ticks)
	)
	 1)
)

(script static void (set_ui_location (short location))
	(set ui_location location)
	(sleep 1)
)

(script static void kill_camera_scripts
	(print "kill camera scripts")
	(kill_active_scripts)
	(if (!= ui_location 0)
		(sleep_forever mainmenu_cam)
	)
	(if (!= ui_location 1)
		(sleep_forever campaign_cam)
	)
	(if (!= ui_location 2)
		(sleep_forever matchmaking_cam)
	)
	(if (!= ui_location 3)
		(sleep_forever custom_cam)
	)
	(if (!= ui_location 4)
		(sleep_forever editor_cam)
	)
	(if (!= ui_location 5)
		(sleep_forever theater_cam)
	)
	(if (!= ui_location 6)
		(sleep_forever settings_cam)
	)
)

(script startup void mainmenu
	(camera_control true)
	(print "mainmenu statup script")
	(wake appearance_characters)
	(campaign_characters)
	(fade_out 0 0 0 0)
	(set ui_location -1)
	(sleep 8)
	(texture_camera_set_aspect_ratio 1.777)
	(fade_in 0 0 0 22)
)

(script dormant void appearance_characters
	(print "appearance characters [static script]")
	(pvs_set_object "spartan_appearance")
	(pvs_set_object "elite_appearance")
	(sleep 1)
	(objects_attach "spartan_appearance" "right_hand" "appearance_ar" "invalid")
	(objects_attach "elite_appearance" "right_hand_elite" "apperance_pr" "invalid")
	(sleep 1)
	(custom_animation_loop "spartan_appearance" "objects\characters\masterchief\masterchief" "ui:rifle:idle:var1" false)
	(custom_animation_loop "elite_appearance" "objects\characters\elite\elite" "ui:pistol:idle:var1" false)
)

(script static void campaign_characters
	(print "campaign characters [static script]")
	(object_create_containing "campaign_")
	(sleep 1)
	(pvs_set_object "campaign_chief")
	(sleep 1)
	(objects_attach "campaign_chief" "right_hand" "campaign_ar" "invalid")
	(sleep 1)
	(custom_animation_loop "campaign_chief" "objects\characters\masterchief\masterchief" "ui:rifle:idle:var1" false)
)

(script static void custom_characters
	(print "campaign characters [static script]")
	(object_create_containing "custom_")
	(sleep_ui 1)
	(pvs_set_object "custom_chief_01")
	(pvs_set_object "custom_elite_01")
	(sleep_ui 1)
	(objects_attach "custom_chief_01" "right_hand" "custom_ar_01" "invalid")
	(objects_attach "custom_elite_01" "right_hand_elite" "custom_pr_01" "invalid")
	(objects_attach "custom_elite_01" "left_hand_elite" "custom_pr_02" "invalid")
	(sleep_ui 1)
	(custom_animation_loop "custom_chief_01" "objects\characters\masterchief\masterchief" "ui:rifle:idle:var3" false)
	(custom_animation_loop "custom_elite_01" "objects\characters\elite\elite" "ui:dual:idle:var1" false)
	(texture_camera_enable_dynamic_lights true)
)

(script static void mainmenu_cam
	(print "mainmenu camera")
	(sleep_ui 10)
	(set_ui_location 0)
	(kill_camera_scripts)
	(object_destroy_containing "editor_")
	(object_destroy_containing "custom_")
	(render_depth_of_field_enable true)
	(render_depth_of_field 1 2 5 10)
	(camera_set "ui_path_01" 0)
	(sleep 90)
	(camera_set "ui_path_02" 500)
	(sleep 250)
	(camera_set "ui_path_03" 500)
	(sleep 250)
	(camera_set "ui_path_04" 500)
	(sleep 250)
	(camera_set "ui_path_05" 500)
	(sleep 250)
	(camera_set "ui_path_06" 500)
	(sleep 250)
	(camera_set "ui_path_07" 500)
	(sleep 250)
	(camera_set "ui_path_08" 500)
	(sleep 250)
	(camera_set "ui_path_09" 500)
	(sleep 250)
	(camera_set "ui_path_10" 400)
	(sleep 200)
	(camera_set "ui_path_11" 400)
	(sleep 200)
	(camera_set "ui_path_12" 400)
	(sleep 200)
	(camera_set "ui_path_01" 300)
	(sleep 300)
)

(script static void campaign_cam
	(print "campaign camera")
	(sleep_ui 10)
	(set_ui_location 1)
	(kill_camera_scripts)
	(object_destroy_containing "custom_")
	(object_destroy_containing "editor_")
	(campaign_characters)
	(render_depth_of_field_enable false)
	(camera_set "campaign_in" 0)
	(sleep 0)
	(camera_set "campaign" 11)
	(sleep 30)
	(camera_set "campaign_path_02" 700)
	(sleep 250)
	(camera_set "campaign_path_03" 700)
	(sleep 250)
	(camera_set "campaign_path_04" 700)
	(sleep 250)
	(camera_set "campaign" 700)
	(sleep 250)
	(sleep_forever)
)

(script static void matchmaking_cam
	(print "matchmaking camera")
	(sleep_ui 10)
	(set_ui_location 2)
	(kill_camera_scripts)
	(object_destroy_containing "custom_")
	(object_destroy_containing "editor_")
	(render_depth_of_field_enable false)
	(camera_set "matchmaking_in" 0)
	(sleep 0)
	(camera_set "matchmaking" 11)
	(sleep 30)
	(camera_set "mm_path_02" 700)
	(sleep 250)
	(camera_set "mm_path_03" 700)
	(sleep 250)
	(camera_set "mm_path_04" 700)
	(sleep 250)
	(camera_set "matchmaking" 700)
	(sleep 250)
	(sleep_forever)
)

(script static void custom_cam
	(print "custom camera")
	(sleep_ui 10)
	(set_ui_location 3)
	(kill_camera_scripts)
	(object_hide "spartan_appearance" false)
	(object_hide "elite_appearance" false)
	(object_create_containing "custom_")
	(object_destroy_containing "editor_")
	(custom_characters)
	(render_depth_of_field_enable true)
	(render_depth_of_field 1 2 5 10)
	(camera_set "custom_in" 0)
	(sleep 0)
	(camera_set "custom_games" 11)
	(sleep 30)
	(camera_set "custom_path_02" 700)
	(sleep 250)
	(camera_set "custom_path_03" 700)
	(sleep 250)
	(camera_set "custom_path_04" 700)
	(sleep 250)
	(camera_set "custom_games" 700)
	(sleep 250)
	(sleep_forever)
)

(script static void editor_characters
	(object_create_anew_containing "editor_")
	(sleep 1)
	(scenery_animation_start_loop "editor_monitor" "levels\ui\mainmenu\objects\monitor_cheap\monitor_cheap" "ui:idle:var1")
)

(script static void editor_cam
	(print "editor camera")
	(sleep_ui 10)
	(set_ui_location 4)
	(kill_camera_scripts)
	(object_destroy_containing "custom_")
	(editor_characters)
	(render_depth_of_field_enable true)
	(render_depth_of_field 1 2 5 10)
	(camera_set "editor_in" 0)
	(sleep 0)
	(camera_set "editor" 11)
	(sleep 30)
	(camera_set "editor_path_02" 500)
	(sleep 250)
	(camera_set "editor_path_03" 700)
	(sleep 250)
	(camera_set "editor_path_04" 700)
	(sleep 250)
	(camera_set "editor" 700)
	(sleep 250)
	(sleep_forever)
)

(script static void theater_cam
	(print "theater camera")
	(sleep_ui 10)
	(set_ui_location 5)
	(kill_camera_scripts)
	(object_destroy_containing "custom_")
	(object_destroy_containing "editor_")
	(render_depth_of_field_enable false)
	(camera_set "theater_in" 0)
	(sleep 0)
	(camera_set "theater" 11)
	(sleep 30)
	(camera_set "theater_path_02" 700)
	(sleep 250)
	(camera_set "theater_path_03" 700)
	(sleep 250)
	(camera_set "theater_path_04" 700)
	(sleep 250)
	(camera_set "theater" 700)
	(sleep 250)
	(sleep_forever)
)

(script static void settings_cam
	(sleep 1)
	(object_hide "spartan_appearance" false)
	(object_hide "elite_appearance" false)
	(print "settings camera")
	(sleep_ui 10)
	(render_depth_of_field_enable true)
	(render_depth_of_field 1 2 5 10)
	(set_ui_location 6)
	(kill_camera_scripts)
	(object_destroy_containing "custom_")
	(object_destroy_containing "editor_")
	(render_depth_of_field_enable false)
	(camera_set "settings_cam" 0)
	(sleep 0)
	(sleep_forever)
)

(script static void leave_settings
	(print "leave settings")
	(mainmenu_cam)
	(sleep_forever)
)

(script static void character_changed
	(sleep 1)
	(effect_new_on_object_marker "objects\characters\elite\fx\shield\shield_recharge" "elite_appearance" "body")
	(effect_new_on_object_marker "objects\characters\masterchief\fx\shield\shield_recharge" "spartan_appearance" "body")
	(sleep_forever)
)
